services:
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - DB_HOST=prof-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - prof-db

  test-app:
    build:
      context: .
      dockerfile: test.Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_HOST=prof-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - prof-db

  prof-db:
    image: postgres:17.4
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - prof-db-data:/var/lib/postgresql/data

volumes:
  prof-db-data:
