services:
  app:
    build: .
    ports:
      - 8001:8000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: [ "--host", "0.0.0.0" ]
    depends_on:
      - prof-db

  prof-db:
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - prof-db-data:/var/lib/postgresql/data

volumes:
  prof-db-data:
